<template>
  <footer
    class="
      u-bg-light
      u-border-t
      u-border-gray
      u-bottom-0
      u-flex
      u-font-serif
      u-justify-space-between
      u-left-0
      u-pos-absolute
      u-px-xxl
      u-py-md
      u-text-lg
      u-w-full
    "
  >
    <slot></slot>
  </footer>
</template>
