/**
 * A set of human-interpretable names that we should display for each active effect key.
 * @enum {String}
 */
export default function registerEffectLocalizationConfig() {
	const effectsKeyLocalizations = {
		'flags.a5e.deathSaveThreshold': 'A5E.effects.keys.flags.deathSaveThreshold',
		'flags.a5e.carryCapacityAbility': 'A5E.effects.keys.flags.carryCapacityAbility',
		'flags.a5e.criticalHitThresholdSpell': 'A5E.effects.keys.flags.criticalHitThresholdSpell',
		'flags.a5e.criticalHitThresholdWeapon': 'A5E.effects.keys.flags.criticalHitThresholdWeapon',
		'flags.a5e.effects.bonuses.abilities': 'A5E.effects.keys.bonuses.ability',
		'flags.a5e.effects.bonuses.attacks': 'A5E.effects.keys.bonuses.attacks',
		'flags.a5e.effects.bonuses.damage': 'A5E.effects.keys.bonuses.damage',
		'flags.a5e.effects.bonuses.healing': 'A5E.effects.keys.bonuses.healing',
		'flags.a5e.effects.bonuses.initiative': 'A5E.effects.keys.bonuses.initiative',
		'flags.a5e.effects.bonuses.skills': 'A5E.effects.keys.bonuses.skill',
		'flags.a5e.effects.conditionImmunities.all': 'A5E.effects.keys.flags.conditionImmunities.all',
		'flags.a5e.effects.damageImmunities.all': 'A5E.effects.keys.flags.damageImmunities.all',
		'flags.a5e.effects.damageResistances.all': 'A5E.effects.keys.flags.damageResistances.all',
		'flags.a5e.effects.damageVulnerabilities.all':
			'A5E.effects.keys.flags.damageVulnerabilities.all',
		'flags.a5e.effects.movement.allDistances': 'A5E.effects.keys.flags.movement.allDistances',
		'flags.a5e.effects.movement.allUnits': 'A5E.effects.keys.flags.movement.allUnits',
		'flags.a5e.effects.expertiseDie': 'A5E.effects.keys.flags.expertiseDie',
		'flags.a5e.effects.statusConditions': 'A5E.effects.keys.flags.statusConditions',
		'flags.a5e.effects.expertiseDice.all': 'A5E.effects.keys.flags.expertiseDice.all',
		'flags.a5e.effects.expertiseDice.allChecks': 'A5E.effects.keys.flags.expertiseDice.allChecks',
		'flags.a5e.effects.expertiseDice.allSaves': 'A5E.effects.keys.flags.expertiseDice.allSaves',
		'flags.a5e.effects.grants.rollMode.attack.all': 'A5E.effects.keys.flags.grantsRollMode.all',
		'flags.a5e.effects.rollMode.abilityCheck.all':
			'A5E.effects.keys.flags.rollMode.abilityChecks.all',
		'flags.a5e.effects.rollMode.abilitySave.all':
			'A5E.effects.keys.flags.rollMode.savingThrows.all',
		'flags.a5e.effects.rollMode.attack.all': 'A5E.effects.keys.flags.rollMode.attack.all',
		'flags.a5e.effects.rollMode.concentration': 'A5E.effects.keys.flags.rollMode.concentration',
		'flags.a5e.effects.rollMode.skillCheck.all': 'A5E.effects.keys.flags.rollMode.skillChecks.all',
		'flags.a5e.effects.senses.allDistances': 'A5E.effects.keys.flags.senses.allDistances',
		'flags.a5e.effects.senses.allUnits': 'A5E.effects.keys.flags.senses.allUnits',

		// Abilities
		'system.abilities.cha.check.bonus': 'A5E.effects.keys.abilities.charismaCheckBonus',
		'system.abilities.cha.check.expertiseDice':
			'A5E.effects.keys.abilities.charismaCheckExpertiseDice',
		'system.abilities.cha.check.rollMode': 'A5E.effects.keys.abilities.charismaCheckRollMode',
		'system.abilities.cha.check.minRoll': 'A5E.effects.keys.abilities.charismaCheckMinRoll',
		'system.abilities.cha.check.maxRoll': 'A5E.effects.keys.abilities.charismaCheckMinRoll',
		'system.abilities.cha.save.bonus': 'A5E.effects.keys.abilities.charismaSaveBonus',
		'system.abilities.cha.save.expertiseDice':
			'A5E.effects.keys.abilities.charismaSaveExpertiseDice',
		'system.abilities.cha.save.proficient': 'A5E.effects.keys.abilities.charismaSaveProficiency',
		'system.abilities.cha.save.rollMode': 'A5E.effects.keys.abilities.charismaSaveRollMode',
		'system.abilities.cha.save.minRoll': 'A5E.effects.keys.abilities.charismaSaveMinRoll',
		'system.abilities.cha.save.maxRoll': 'A5E.effects.keys.abilities.charismaSaveMinRoll',
		'system.abilities.cha.value': 'A5E.effects.keys.abilities.charismaValue',

		'system.abilities.con.check.bonus': 'A5E.effects.keys.abilities.constitutionCheckBonus',
		'system.abilities.con.check.expertiseDice':
			'A5E.effects.keys.abilities.constitutionCheckExpertiseDice',
		'system.abilities.con.check.rollMode': 'A5E.effects.keys.abilities.constitutionCheckRollMode',
		'system.abilities.con.check.minRoll': 'A5E.effects.keys.abilities.constitutionCheckMinRoll',
		'system.abilities.con.check.maxRoll': 'A5E.effects.keys.abilities.constitutionCheckMinRoll',
		'system.abilities.con.save.bonus': 'A5E.effects.keys.abilities.constitutionSaveBonus',
		'system.abilities.con.save.concentrationBonus':
			'A5E.effects.keys.abilities.constitutionSaveConcentrationBonus',
		'system.abilities.con.save.expertiseDice':
			'A5E.effects.keys.abilities.constitutionSaveExpertiseDice',
		'system.abilities.con.save.proficient':
			'A5E.effects.keys.abilities.constitutionSaveProficiency',
		'system.abilities.con.value': 'A5E.effects.keys.abilities.constitutionValue',
		'system.abilities.con.save.rollMode': 'A5E.effects.keys.abilities.constitutionSaveRollMode',
		'system.abilities.con.save.minRoll': 'A5E.effects.keys.abilities.constitutionSaveMinRoll',
		'system.abilities.con.save.maxRoll': 'A5E.effects.keys.abilities.constitutionSaveMinRoll',

		'system.abilities.dex.check.bonus': 'A5E.effects.keys.abilities.dexterityCheckBonus',
		'system.abilities.dex.check.expertiseDice':
			'A5E.effects.keys.abilities.dexterityCheckExpertiseDice',
		'system.abilities.dex.check.rollMode': 'A5E.effects.keys.abilities.dexterityCheckRollMode',
		'system.abilities.dex.check.minRoll': 'A5E.effects.keys.abilities.dexterityCheckMinRoll',
		'system.abilities.dex.check.maxRoll': 'A5E.effects.keys.abilities.dexterityCheckMinRoll',
		'system.abilities.dex.save.bonus': 'A5E.effects.keys.abilities.dexteritySaveBonus',
		'system.abilities.dex.save.expertiseDice':
			'A5E.effects.keys.abilities.dexteritySaveExpertiseDice',
		'system.abilities.dex.save.proficient': 'A5E.effects.keys.abilities.dexteritySaveProficiency',
		'system.abilities.dex.save.rollMode': 'A5E.effects.keys.abilities.dexteritySaveRollMode',
		'system.abilities.dex.save.minRoll': 'A5E.effects.keys.abilities.dexteritySaveMinRoll',
		'system.abilities.dex.save.maxRoll': 'A5E.effects.keys.abilities.dexteritySaveMinRoll',
		'system.abilities.dex.value': 'A5E.effects.keys.abilities.dexterityValue',

		'system.abilities.int.check.bonus': 'A5E.effects.keys.abilities.intelligenceCheckBonus',
		'system.abilities.int.check.expertiseDice':
			'A5E.effects.keys.abilities.intelligenceCheckExpertiseDice',
		'system.abilities.int.check.rollMode': 'A5E.effects.keys.abilities.intelligenceCheckRollMode',
		'system.abilities.int.check.minRoll': 'A5E.effects.keys.abilities.intelligenceCheckMinRoll',
		'system.abilities.int.check.maxRoll': 'A5E.effects.keys.abilities.intelligenceCheckMinRoll',
		'system.abilities.int.save.bonus': 'A5E.effects.keys.abilities.intelligenceSaveBonus',
		'system.abilities.int.save.expertiseDice':
			'A5E.effects.keys.abilities.intelligenceSaveExpertiseDice',
		'system.abilities.int.save.proficient':
			'A5E.effects.keys.abilities.intelligenceSaveProficiency',
		'system.abilities.int.save.rollMode': 'A5E.effects.keys.abilities.intelligenceSaveRollMode',
		'system.abilities.int.save.minRoll': 'A5E.effects.keys.abilities.intelligenceSaveMinRoll',
		'system.abilities.int.save.maxRoll': 'A5E.effects.keys.abilities.intelligenceSaveMinRoll',
		'system.abilities.int.value': 'A5E.effects.keys.abilities.intelligenceValue',

		'system.abilities.str.check.bonus': 'A5E.effects.keys.abilities.strengthCheckBonus',
		'system.abilities.str.check.expertiseDice':
			'A5E.effects.keys.abilities.strengthCheckExpertiseDice',
		'system.abilities.str.check.rollMode': 'A5E.effects.keys.abilities.strengthCheckRollMode',
		'system.abilities.str.check.minRoll': 'A5E.effects.keys.abilities.strengthCheckMinRoll',
		'system.abilities.str.check.maxRoll': 'A5E.effects.keys.abilities.strengthCheckMinRoll',
		'system.abilities.str.save.bonus': 'A5E.effects.keys.abilities.strengthSaveBonus',
		'system.abilities.str.save.expertiseDice':
			'A5E.effects.keys.abilities.strengthSaveExpertiseDice',
		'system.abilities.str.save.proficient': 'A5E.effects.keys.abilities.strengthSaveProficiency',
		'system.abilities.str.save.rollMode': 'A5E.effects.keys.abilities.strengthSaveRollMode',
		'system.abilities.str.save.minRoll': 'A5E.effects.keys.abilities.strengthSaveMinRoll',
		'system.abilities.str.save.maxRoll': 'A5E.effects.keys.abilities.strengthSaveMinRoll',
		'system.abilities.str.value': 'A5E.effects.keys.abilities.strengthValue',

		'system.abilities.wis.check.bonus': 'A5E.effects.keys.abilities.wisdomCheckBonus',
		'system.abilities.wis.check.expertiseDice':
			'A5E.effects.keys.abilities.wisdomCheckExpertiseDice',
		'system.abilities.wis.check.rollMode': 'A5E.effects.keys.abilities.wisdomCheckRollMode',
		'system.abilities.wis.check.minRoll': 'A5E.effects.keys.abilities.wisdomCheckMinRoll',
		'system.abilities.wis.check.maxRoll': 'A5E.effects.keys.abilities.wisdomCheckMinRoll',
		'system.abilities.wis.save.bonus': 'A5E.effects.keys.abilities.wisdomSaveBonus',
		'system.abilities.wis.save.expertiseDice': 'A5E.effects.keys.abilities.wisdomSaveExpertiseDice',
		'system.abilities.wis.save.proficient': 'A5E.effects.keys.abilities.wisdomSaveProficiency',
		'system.abilities.wis.save.rollMode': 'A5E.effects.keys.abilities.wisdomSaveRollMode',
		'system.abilities.wis.save.minRoll': 'A5E.effects.keys.abilities.wisdomSaveMinRoll',
		'system.abilities.wis.save.maxRoll': 'A5E.effects.keys.abilities.wisdomSaveMinRoll',
		'system.abilities.wis.value': 'A5E.effects.keys.abilities.wisdomValue',

		'system.attributes.ac.baseFormula': 'A5E.effects.keys.armorClass.baseFormula',
		'system.attributes.ac.changes.bonuses.value': 'A5E.effects.keys.armorClass.bonuses',
		'system.attributes.ac.value': 'A5E.effects.keys.armorClass.value',
		'system.attributes.attunement.current': 'A5E.effects.keys.attunementCurrent',
		'system.attributes.attunement.max': 'A5E.effects.keys.attunementMax',
		'system.attributes.casterLevel': 'A5E.effects.keys.casterLevel',
		'system.attributes.corruption': 'A5E.effects.keys.corruption',
		'system.attributes.death.failure': 'A5E.effects.keys.deathSaveFailures',
		'system.attributes.death.success': 'A5E.effects.keys.deathSaveSuccesses',
		'system.attributes.exertion.current': 'A5E.effects.keys.exertionCurrent',
		'system.attributes.exertion.max': 'A5E.effects.keys.exertionMax',
		'system.attributes.exertion.recoverOnRest': 'A5E.effects.keys.recoverExertionOnShortRest',
		'system.attributes.fatigue': 'A5E.effects.keys.fatigue',
		'system.attributes.favorPoints.current': 'A5E.effects.keys.favorCurrent',
		'system.attributes.favorPoints.max': 'A5E.effects.keys.favorMax',
		'system.attributes.hitDice.d20.current': 'A5E.effects.keys.hitDice.d20Current',
		'system.attributes.hitDice.d20.total': 'A5E.effects.keys.hitDice.d20Max',
		'system.attributes.hitDice.d12.current': 'A5E.effects.keys.hitDice.d12Current',
		'system.attributes.hitDice.d12.total': 'A5E.effects.keys.hitDice.d12Max',
		'system.attributes.hitDice.d10.current': 'A5E.effects.keys.hitDice.d10Current',
		'system.attributes.hitDice.d10.total': 'A5E.effects.keys.hitDice.d10Max',
		'system.attributes.hitDice.d6.current': 'A5E.effects.keys.hitDice.d6Current',
		'system.attributes.hitDice.d6.total': 'A5E.effects.keys.hitDice.d6Max',
		'system.attributes.hitDice.d8.current': 'A5E.effects.keys.hitDice.d8Current',
		'system.attributes.hitDice.d8.total': 'A5E.effects.keys.hitDice.d8Max',
		'system.attributes.hitDice.d4.current': 'A5E.effects.keys.hitDice.d4Current',
		'system.attributes.hitDice.d4.total': 'A5E.effects.keys.hitDice.d4Max',
		'system.attributes.hp.baseMax': 'A5E.effects.keys.hitPoints.baseMax',
		'system.attributes.hp.bonus': 'A5E.effects.keys.hitPoints.bonus',
		'system.attributes.hp.value': 'A5E.effects.keys.hitPoints.current',
		'system.attributes.hp.max': 'A5E.effects.keys.hitPoints.max',
		'system.attributes.hp.temp': 'A5E.effects.keys.hitPoints.temp',
		'system.attributes.inebriated': 'A5E.effects.keys.inebriated',
		'system.attributes.initiative.ability': 'A5E.effects.keys.initiativeAbility',
		'system.attributes.initiative.expertiseDice': 'A5E.effects.keys.initiativeExpertiseDice',
		'system.attributes.initiative.minRoll': 'A5E.effects.keys.initiativeMinRoll',
		'system.attributes.initiative.maxRoll': 'A5E.effects.keys.initiativeMaxRoll',
		'system.attributes.initiative.rollMode': 'A5E.effects.keys.initiativeRollMode',
		'system.attributes.inspiration': 'A5E.effects.keys.inspiration',
		'system.attributes.maneuverDC': 'A5E.effects.keys.maneuverDC',
		'system.attributes.movement.burrow.distance': 'A5E.effects.keys.movement.burrowDistance',
		'system.attributes.movement.burrow.unit': 'A5E.effects.keys.movement.burrowUnit',
		'system.attributes.movement.climb.distance': 'A5E.effects.keys.movement.climbDistance',
		'system.attributes.movement.climb.unit': 'A5E.effects.keys.movement.climbUnit',
		'system.attributes.movement.fly.distance': 'A5E.effects.keys.movement.flyDistance',
		'system.attributes.movement.fly.unit': 'A5E.effects.keys.movement.flyUnit',
		'system.attributes.movement.swim.distance': 'A5E.effects.keys.movement.swimDistance',
		'system.attributes.movement.swim.unit': 'A5E.effects.keys.movement.swimUnit',
		'system.attributes.movement.traits.hover': 'A5E.effects.keys.movement.hover',
		'system.attributes.movement.walk.distance': 'A5E.effects.keys.movement.walkDistance',
		'system.attributes.movement.walk.unit': 'A5E.effects.keys.movement.walkUnit',
		'system.attributes.prof': 'A5E.effects.keys.proficiencyBonus',
		'system.attributes.senses.blindsight.distance': 'A5E.effects.keys.vision.blindsightDistance',
		'system.attributes.senses.blindsight.unit': 'A5E.effects.keys.vision.blindsightUnit',
		'system.attributes.senses.blindsight.otherwiseBlind':
			'A5E.effects.keys.vision.blindsightOtherwiseBlind',
		'system.attributes.senses.darkvision.distance': 'A5E.effects.keys.vision.darkvisionDistance',
		'system.attributes.senses.darkvision.unit': 'A5E.effects.keys.vision.darkvisionUnit',
		'system.attributes.senses.tremorsense.distance': 'A5E.effects.keys.vision.tremorsenseDistance',
		'system.attributes.senses.tremorsense.unit': 'A5E.effects.keys.vision.tremorsenseUnit',
		'system.attributes.senses.truesight.distance': 'A5E.effects.keys.vision.truesightDistance',
		'system.attributes.senses.truesight.unit': 'A5E.effects.keys.vision.truesightUnit',
		'system.attributes.spellcasting': 'A5E.effects.keys.spellcastingAbility',
		'system.attributes.spellDC': 'A5E.effects.keys.spellDC',
		'system.attributes.strife': 'A5E.effects.keys.strife',
		'system.bonuses.abilities.check': 'A5E.effects.keys.bonuses.check',
		'system.bonuses.abilities.save': 'A5E.effects.keys.bonuses.save',
		'system.bonuses.abilities.skill': 'A5E.effects.keys.bonuses.skill',
		'system.bonuses.hitPoint': 'A5E.effects.keys.bonuses.hitPoint',
		'system.bonuses.exertion': 'A5E.effects.keys.bonuses.exertion',
		'system.bonuses.maneuverDC': 'A5E.effects.keys.bonuses.maneuverDC',
		'system.bonuses.spellDC': 'A5E.effects.keys.bonuses.spellDC',
		'system.currency.cp': 'A5E.effects.keys.currency.cp',
		'system.currency.cr': 'A5E.effects.keys.currency.cr',
		'system.currency.ep': 'A5E.effects.keys.currency.ep',
		'system.currency.gp': 'A5E.effects.keys.currency.gp',
		'system.currency.pp': 'A5E.effects.keys.currency.pp',
		'system.currency.sp': 'A5E.effects.keys.currency.sp',
		'system.details.creatureTypes': 'A5E.effects.keys.details.creatureTypes',
		'system.details.cr': 'A5E.effects.keys.details.cr',
		'system.details.elite': 'A5E.effects.keys.details.elite',
		'system.details.isSwarm': 'A5E.effects.keys.details.isSwarm',
		'system.details.isShapechanger': 'A5E.effects.keys.details.isShapeChanger',
		'system.proficiencies.armor': 'A5E.effects.keys.proficiencies.armor',
		'system.proficiencies.languages': 'A5E.effects.keys.proficiencies.languages',
		'system.proficiencies.tools': 'A5E.effects.keys.proficiencies.tools',
		'system.proficiencies.traditions': 'A5E.effects.keys.proficiencies.traditions',
		'system.proficiencies.weapons': 'A5E.effects.keys.proficiencies.weapons',
		'system.resources.primary.hideMax': 'A5E.effects.keys.resources.primary.hideMax',
		'system.resources.primary.label': 'A5E.effects.keys.resources.primary.label',
		'system.resources.primary.max': 'A5E.effects.keys.resources.primary.max',
		'system.resources.primary.per': 'A5E.effects.keys.resources.primary.per',
		'system.resources.primary.recharge.formula':
			'A5E.effects.keys.resources.primary.rechargeFormula',
		'system.resources.primary.recharge.threshold':
			'A5E.effects.keys.resources.primary.rechargeThreshold',
		'system.resources.primary.value': 'A5E.effects.keys.resources.primary.value',
		'system.resources.quaternary.hideMax': 'A5E.effects.keys.resources.quaternary.hideMax',
		'system.resources.quaternary.label': 'A5E.effects.keys.resources.quaternary.label',
		'system.resources.quaternary.max': 'A5E.effects.keys.resources.quaternary.max',
		'system.resources.quaternary.per': 'A5E.effects.keys.resources.quaternary.per',
		'system.resources.quaternary.recharge.formula':
			'A5E.effects.keys.resources.quaternary.rechargeFormula',
		'system.resources.quaternary.recharge.threshold':
			'A5E.effects.keys.resources.quaternary.rechargeThreshold',
		'system.resources.quaternary.value': 'A5E.effects.keys.resources.quaternary.value',
		'system.resources.secondary.hideMax': 'A5E.effects.keys.resources.secondary.hideMax',
		'system.resources.secondary.label': 'A5E.effects.keys.resources.secondary.label',
		'system.resources.secondary.max': 'A5E.effects.keys.resources.secondary.max',
		'system.resources.secondary.per': 'A5E.effects.keys.resources.secondary.per',
		'system.resources.secondary.recharge.formula':
			'A5E.effects.keys.resources.secondary.rechargeFormula',
		'system.resources.secondary.recharge.threshold':
			'A5E.effects.keys.resources.secondary.rechargeThreshold',
		'system.resources.secondary.value': 'A5E.effects.keys.resources.secondary.value',
		'system.resources.tertiary.hideMax': 'A5E.effects.keys.resources.tertiary.hideMax',
		'system.resources.tertiary.label': 'A5E.effects.keys.resources.tertiary.label',
		'system.resources.tertiary.max': 'A5E.effects.keys.resources.tertiary.max',
		'system.resources.tertiary.per': 'A5E.effects.keys.resources.tertiary.per',
		'system.resources.tertiary.recharge.formula':
			'A5E.effects.keys.resources.tertiary.rechargeFormula',
		'system.resources.tertiary.recharge.threshold':
			'A5E.effects.keys.resources.tertiary.rechargeThreshold',
		'system.resources.tertiary.value': 'A5E.effects.keys.resources.tertiary.value',

		// Rolls
		'system.rolls.meleeSpellAttack.outgoing.expertiseDice':
			'A5E.effects.keys.rolls.outgoing.meleeSpellAttack.expertise',
		'system.rolls.meleeSpellAttack.outgoing.minRoll':
			'A5E.effects.keys.rolls.outgoing.meleeSpellAttack.minRoll',
		'system.rolls.meleeSpellAttack.outgoing.maxRoll':
			'A5E.effects.keys.rolls.outgoing.meleeSpellAttack.maxRoll',
		'system.rolls.meleeSpellAttack.outgoing.rollMode':
			'A5E.effects.keys.rolls.outgoing.meleeSpellAttack.rollMode',
		'system.rolls.meleeSpellAttack.incoming.rollMode':
			'A5E.effects.keys.rolls.incoming.meleeSpellAttack.rollMode',

		'system.rolls.meleeWeaponAttack.outgoing.expertiseDice':
			'A5E.effects.keys.rolls.outgoing.meleeWeaponAttack.expertise',
		'system.rolls.meleeWeaponAttack.outgoing.minRoll':
			'A5E.effects.keys.rolls.outgoing.meleeWeaponAttack.minRoll',
		'system.rolls.meleeWeaponAttack.outgoing.maxRoll':
			'A5E.effects.keys.rolls.outgoing.meleeWeaponAttack.maxRoll',
		'system.rolls.meleeWeaponAttack.outgoing.rollMode':
			'A5E.effects.keys.rolls.outgoing.meleeWeaponAttack.rollMode',
		'system.rolls.meleeWeaponAttack.incoming.rollMode':
			'A5E.effects.keys.rolls.incoming.meleeWeaponAttack.rollMode',

		'system.rolls.rangedSpellAttack.outgoing.expertiseDice':
			'A5E.effects.keys.rolls.outgoing.rangedSpellAttack.expertise',
		'system.rolls.rangedSpellAttack.outgoing.minRoll':
			'A5E.effects.keys.rolls.outgoing.rangedSpellAttack.minRoll',
		'system.rolls.rangedSpellAttack.outgoing.maxRoll':
			'A5E.effects.keys.rolls.outgoing.rangedSpellAttack.maxRoll',
		'system.rolls.rangedSpellAttack.outgoing.rollMode':
			'A5E.effects.keys.rolls.outgoing.rangedSpellAttack.rollMode',
		'system.rolls.rangedSpellAttack.incoming.rollMode':
			'A5E.effects.keys.rolls.incoming.rangedSpellAttack.rollMode',

		'system.rolls.rangedWeaponAttack.outgoing.expertiseDice':
			'A5E.effects.keys.rolls.outgoing.rangedWeaponAttack.expertise',
		'system.rolls.rangedWeaponAttack.outgoing.minRoll':
			'A5E.effects.keys.rolls.outgoing.rangedWeaponAttack.minRoll',
		'system.rolls.rangedWeaponAttack.outgoing.maxRoll':
			'A5E.effects.keys.rolls.outgoing.rangedWeaponAttack.maxRoll',
		'system.rolls.rangedWeaponAttack.outgoing.rollMode':
			'A5E.effects.keys.rolls.outgoing.rangedWeaponAttack.rollMode',
		'system.rolls.rangedWeaponAttack.incoming.rollMode':
			'A5E.effects.keys.rolls.incoming.rangedWeaponAttack.rollMode',

		'system.rolls.death.expertiseDice': 'A5E.effects.keys.rolls.death.expertise',
		'system.rolls.death.maxRoll': 'A5E.effects.keys.rolls.death.maxRoll',
		'system.rolls.death.minRoll': 'A5E.effects.keys.rolls.death.minRoll',
		'system.rolls.death.rollMode': 'A5E.effects.keys.rolls.death.rollMode',

		// Skills
		'system.skills.acr.ability': 'A5E.effects.keys.skills.acr.defaultAbility',
		'system.skills.acr.bonuses.check': 'A5E.effects.keys.skills.acr.checkBonus',
		'system.skills.acr.bonuses.passive': 'A5E.effects.keys.skills.acr.passiveBonus',
		'system.skills.acr.expertiseDice': 'A5E.effects.keys.skills.acr.expertiseDice',
		'system.skills.acr.minRoll': 'A5E.effects.keys.skills.acr.minRoll',
		'system.skills.acr.maxRoll': 'A5E.effects.keys.skills.acr.maxRoll',
		'system.skills.acr.proficient': 'A5E.effects.keys.skills.acr.proficient',
		'system.skills.acr.rollMode': 'A5E.effects.keys.skills.acr.rollMode',
		'system.skills.acr.specialties': 'A5E.effects.keys.skills.acr.specialties',
		'system.skills.acr.value': 'A5E.effects.keys.skills.acr.value',

		'system.skills.ani.ability': 'A5E.effects.keys.skills.ani.defaultAbility',
		'system.skills.ani.bonuses.check': 'A5E.effects.keys.skills.ani.checkBonus',
		'system.skills.ani.bonuses.passive': 'A5E.effects.keys.skills.ani.passiveBonus',
		'system.skills.ani.expertiseDice': 'A5E.effects.keys.skills.ani.expertiseDice',
		'system.skills.ani.minRoll': 'A5E.effects.keys.skills.ani.minRoll',
		'system.skills.ani.maxRoll': 'A5E.effects.keys.skills.ani.maxRoll',
		'system.skills.ani.proficient': 'A5E.effects.keys.skills.ani.proficient',
		'system.skills.ani.rollMode': 'A5E.effects.keys.skills.ani.rollMode',
		'system.skills.ani.specialties': 'A5E.effects.keys.skills.ani.specialties',
		'system.skills.ani.value': 'A5E.effects.keys.skills.ani.value',

		'system.skills.arc.ability': 'A5E.effects.keys.skills.arc.defaultAbility',
		'system.skills.arc.bonuses.check': 'A5E.effects.keys.skills.arc.checkBonus',
		'system.skills.arc.bonuses.passive': 'A5E.effects.keys.skills.arc.passiveBonus',
		'system.skills.arc.expertiseDice': 'A5E.effects.keys.skills.arc.expertiseDice',
		'system.skills.arc.minRoll': 'A5E.effects.keys.skills.arc.minRoll',
		'system.skills.arc.maxRoll': 'A5E.effects.keys.skills.arc.maxRoll',
		'system.skills.arc.rollMode': 'A5E.effects.keys.skills.arc.rollMode',
		'system.skills.arc.proficient': 'A5E.effects.keys.skills.arc.proficient',
		'system.skills.arc.specialties': 'A5E.effects.keys.skills.arc.specialties',
		'system.skills.arc.value': 'A5E.effects.keys.skills.arc.value',

		'system.skills.ath.ability': 'A5E.effects.keys.skills.ath.defaultAbility',
		'system.skills.ath.bonuses.check': 'A5E.effects.keys.skills.ath.checkBonus',
		'system.skills.ath.bonuses.passive': 'A5E.effects.keys.skills.ath.passiveBonus',
		'system.skills.ath.expertiseDice': 'A5E.effects.keys.skills.ath.expertiseDice',
		'system.skills.ath.minRoll': 'A5E.effects.keys.skills.ath.minRoll',
		'system.skills.ath.maxRoll': 'A5E.effects.keys.skills.ath.maxRoll',
		'system.skills.ath.rollMode': 'A5E.effects.keys.skills.ath.rollMode',
		'system.skills.ath.proficient': 'A5E.effects.keys.skills.ath.proficient',
		'system.skills.ath.specialties': 'A5E.effects.keys.skills.ath.specialties',
		'system.skills.ath.value': 'A5E.effects.keys.skills.ath.value',

		'system.skills.cul.ability': 'A5E.effects.keys.skills.cul.defaultAbility',
		'system.skills.cul.bonuses.check': 'A5E.effects.keys.skills.cul.checkBonus',
		'system.skills.cul.bonuses.passive': 'A5E.effects.keys.skills.cul.passiveBonus',
		'system.skills.cul.expertiseDice': 'A5E.effects.keys.skills.cul.expertiseDice',
		'system.skills.cul.minRoll': 'A5E.effects.keys.skills.cul.minRoll',
		'system.skills.cul.maxRoll': 'A5E.effects.keys.skills.cul.maxRoll',
		'system.skills.cul.rollMode': 'A5E.effects.keys.skills.cul.rollMode',
		'system.skills.cul.proficient': 'A5E.effects.keys.skills.cul.proficient',
		'system.skills.cul.specialties': 'A5E.effects.keys.skills.cul.specialties',
		'system.skills.cul.value': 'A5E.effects.keys.skills.cul.value',

		'system.skills.dec.ability': 'A5E.effects.keys.skills.dec.defaultAbility',
		'system.skills.dec.bonuses.check': 'A5E.effects.keys.skills.dec.checkBonus',
		'system.skills.dec.bonuses.passive': 'A5E.effects.keys.skills.dec.passiveBonus',
		'system.skills.dec.expertiseDice': 'A5E.effects.keys.skills.dec.expertiseDice',
		'system.skills.dec.minRoll': 'A5E.effects.keys.skills.dec.minRoll',
		'system.skills.dec.maxRoll': 'A5E.effects.keys.skills.dec.maxRoll',
		'system.skills.dec.rollMode': 'A5E.effects.keys.skills.dec.rollMode',
		'system.skills.dec.proficient': 'A5E.effects.keys.skills.dec.proficient',
		'system.skills.dec.specialties': 'A5E.effects.keys.skills.dec.specialties',
		'system.skills.dec.value': 'A5E.effects.keys.skills.dec.value',

		'system.skills.eng.ability': 'A5E.effects.keys.skills.eng.defaultAbility',
		'system.skills.eng.bonuses.check': 'A5E.effects.keys.skills.eng.checkBonus',
		'system.skills.eng.bonuses.passive': 'A5E.effects.keys.skills.eng.passiveBonus',
		'system.skills.eng.expertiseDice': 'A5E.effects.keys.skills.eng.expertiseDice',
		'system.skills.eng.minRoll': 'A5E.effects.keys.skills.eng.minRoll',
		'system.skills.eng.maxRoll': 'A5E.effects.keys.skills.eng.maxRoll',
		'system.skills.eng.rollMode': 'A5E.effects.keys.skills.eng.rollMode',
		'system.skills.eng.proficient': 'A5E.effects.keys.skills.eng.proficient',
		'system.skills.eng.specialties': 'A5E.effects.keys.skills.eng.specialties',
		'system.skills.eng.value': 'A5E.effects.keys.skills.eng.value',

		'system.skills.his.ability': 'A5E.effects.keys.skills.his.defaultAbility',
		'system.skills.his.bonuses.check': 'A5E.effects.keys.skills.his.checkBonus',
		'system.skills.his.bonuses.passive': 'A5E.effects.keys.skills.his.passiveBonus',
		'system.skills.his.expertiseDice': 'A5E.effects.keys.skills.his.expertiseDice',
		'system.skills.his.minRoll': 'A5E.effects.keys.skills.his.minRoll',
		'system.skills.his.maxRoll': 'A5E.effects.keys.skills.his.maxRoll',
		'system.skills.his.rollMode': 'A5E.effects.keys.skills.his.rollMode',
		'system.skills.his.proficient': 'A5E.effects.keys.skills.his.proficient',
		'system.skills.his.specialties': 'A5E.effects.keys.skills.his.specialties',
		'system.skills.his.value': 'A5E.effects.keys.skills.his.value',

		'system.skills.ins.ability': 'A5E.effects.keys.skills.ins.defaultAbility',
		'system.skills.ins.bonuses.check': 'A5E.effects.keys.skills.ins.checkBonus',
		'system.skills.ins.bonuses.passive': 'A5E.effects.keys.skills.ins.passiveBonus',
		'system.skills.ins.expertiseDice': 'A5E.effects.keys.skills.ins.expertiseDice',
		'system.skills.ins.minRoll': 'A5E.effects.keys.skills.ins.minRoll',
		'system.skills.ins.maxRoll': 'A5E.effects.keys.skills.ins.maxRoll',
		'system.skills.ins.rollMode': 'A5E.effects.keys.skills.ins.rollMode',
		'system.skills.ins.proficient': 'A5E.effects.keys.skills.ins.proficient',
		'system.skills.ins.specialties': 'A5E.effects.keys.skills.ins.specialties',
		'system.skills.ins.value': 'A5E.effects.keys.skills.ins.value',

		'system.skills.itm.ability': 'A5E.effects.keys.skills.itm.defaultAbility',
		'system.skills.itm.bonuses.check': 'A5E.effects.keys.skills.itm.checkBonus',
		'system.skills.itm.bonuses.passive': 'A5E.effects.keys.skills.itm.passiveBonus',
		'system.skills.itm.expertiseDice': 'A5E.effects.keys.skills.itm.expertiseDice',
		'system.skills.itm.minRoll': 'A5E.effects.keys.skills.itm.minRoll',
		'system.skills.itm.maxRoll': 'A5E.effects.keys.skills.itm.maxRoll',
		'system.skills.itm.rollMode': 'A5E.effects.keys.skills.itm.rollMode',
		'system.skills.itm.proficient': 'A5E.effects.keys.skills.itm.proficient',
		'system.skills.itm.specialties': 'A5E.effects.keys.skills.itm.specialties',
		'system.skills.itm.value': 'A5E.effects.keys.skills.itm.value',

		'system.skills.inv.ability': 'A5E.effects.keys.skills.inv.defaultAbility',
		'system.skills.inv.bonuses.check': 'A5E.effects.keys.skills.inv.checkBonus',
		'system.skills.inv.bonuses.passive': 'A5E.effects.keys.skills.inv.passiveBonus',
		'system.skills.inv.expertiseDice': 'A5E.effects.keys.skills.inv.expertiseDice',
		'system.skills.inv.minRoll': 'A5E.effects.keys.skills.inv.minRoll',
		'system.skills.inv.maxRoll': 'A5E.effects.keys.skills.inv.maxRoll',
		'system.skills.inv.rollMode': 'A5E.effects.keys.skills.inv.rollMode',
		'system.skills.inv.proficient': 'A5E.effects.keys.skills.inv.proficient',
		'system.skills.inv.specialties': 'A5E.effects.keys.skills.inv.specialties',
		'system.skills.inv.value': 'A5E.effects.keys.skills.inv.value',

		'system.skills.med.ability': 'A5E.effects.keys.skills.med.defaultAbility',
		'system.skills.med.bonuses.check': 'A5E.effects.keys.skills.med.checkBonus',
		'system.skills.med.bonuses.passive': 'A5E.effects.keys.skills.med.passiveBonus',
		'system.skills.med.expertiseDice': 'A5E.effects.keys.skills.med.expertiseDice',
		'system.skills.med.minRoll': 'A5E.effects.keys.skills.med.minRoll',
		'system.skills.med.maxRoll': 'A5E.effects.keys.skills.med.maxRoll',
		'system.skills.med.rollMode': 'A5E.effects.keys.skills.med.rollMode',
		'system.skills.med.proficient': 'A5E.effects.keys.skills.med.proficient',
		'system.skills.med.specialties': 'A5E.effects.keys.skills.med.specialties',
		'system.skills.med.value': 'A5E.effects.keys.skills.med.value',

		'system.skills.nat.ability': 'A5E.effects.keys.skills.nat.defaultAbility',
		'system.skills.nat.bonuses.check': 'A5E.effects.keys.skills.nat.checkBonus',
		'system.skills.nat.bonuses.passive': 'A5E.effects.keys.skills.nat.passiveBonus',
		'system.skills.nat.expertiseDice': 'A5E.effects.keys.skills.nat.expertiseDice',
		'system.skills.nat.minRoll': 'A5E.effects.keys.skills.nat.minRoll',
		'system.skills.nat.maxRoll': 'A5E.effects.keys.skills.nat.maxRoll',
		'system.skills.nat.rollMode': 'A5E.effects.keys.skills.nat.rollMode',
		'system.skills.nat.proficient': 'A5E.effects.keys.skills.nat.proficient',
		'system.skills.nat.specialties': 'A5E.effects.keys.skills.nat.specialties',
		'system.skills.nat.value': 'A5E.effects.keys.skills.nat.value',

		'system.skills.prc.ability': 'A5E.effects.keys.skills.prc.defaultAbility',
		'system.skills.prc.bonuses.check': 'A5E.effects.keys.skills.prc.checkBonus',
		'system.skills.prc.bonuses.passive': 'A5E.effects.keys.skills.prc.passiveBonus',
		'system.skills.prc.expertiseDice': 'A5E.effects.keys.skills.prc.expertiseDice',
		'system.skills.prc.minRoll': 'A5E.effects.keys.skills.prc.minRoll',
		'system.skills.prc.maxRoll': 'A5E.effects.keys.skills.prc.maxRoll',
		'system.skills.prc.rollMode': 'A5E.effects.keys.skills.prc.rollMode',
		'system.skills.prc.proficient': 'A5E.effects.keys.skills.prc.proficient',
		'system.skills.prc.specialties': 'A5E.effects.keys.skills.prc.specialties',
		'system.skills.prc.value': 'A5E.effects.keys.skills.prc.value',

		'system.skills.prf.ability': 'A5E.effects.keys.skills.prf.defaultAbility',
		'system.skills.prf.bonuses.check': 'A5E.effects.keys.skills.prf.checkBonus',
		'system.skills.prf.bonuses.passive': 'A5E.effects.keys.skills.prf.passiveBonus',
		'system.skills.prf.expertiseDice': 'A5E.effects.keys.skills.prf.expertiseDice',
		'system.skills.prf.minRoll': 'A5E.effects.keys.skills.prf.minRoll',
		'system.skills.prf.maxRoll': 'A5E.effects.keys.skills.prf.maxRoll',
		'system.skills.prf.rollMode': 'A5E.effects.keys.skills.prf.rollMode',
		'system.skills.prf.proficient': 'A5E.effects.keys.skills.prf.proficient',
		'system.skills.prf.specialties': 'A5E.effects.keys.skills.prf.specialties',
		'system.skills.prf.value': 'A5E.effects.keys.skills.prf.value',

		'system.skills.per.ability': 'A5E.effects.keys.skills.per.defaultAbility',
		'system.skills.per.bonuses.check': 'A5E.effects.keys.skills.per.checkBonus',
		'system.skills.per.bonuses.passive': 'A5E.effects.keys.skills.per.passiveBonus',
		'system.skills.per.expertiseDice': 'A5E.effects.keys.skills.per.expertiseDice',
		'system.skills.per.minRoll': 'A5E.effects.keys.skills.per.minRoll',
		'system.skills.per.maxRoll': 'A5E.effects.keys.skills.per.maxRoll',
		'system.skills.per.rollMode': 'A5E.effects.keys.skills.per.rollMode',
		'system.skills.per.proficient': 'A5E.effects.keys.skills.per.proficient',
		'system.skills.per.specialties': 'A5E.effects.keys.skills.per.specialties',
		'system.skills.per.value': 'A5E.effects.keys.skills.per.value',

		'system.skills.rel.ability': 'A5E.effects.keys.skills.rel.defaultAbility',
		'system.skills.rel.bonuses.check': 'A5E.effects.keys.skills.rel.checkBonus',
		'system.skills.rel.bonuses.passive': 'A5E.effects.keys.skills.rel.passiveBonus',
		'system.skills.rel.expertiseDice': 'A5E.effects.keys.skills.rel.expertiseDice',
		'system.skills.rel.minRoll': 'A5E.effects.keys.skills.rel.minRoll',
		'system.skills.rel.maxRoll': 'A5E.effects.keys.skills.rel.maxRoll',
		'system.skills.rel.rollMode': 'A5E.effects.keys.skills.rel.rollMode',
		'system.skills.rel.proficient': 'A5E.effects.keys.skills.rel.proficient',
		'system.skills.rel.specialties': 'A5E.effects.keys.skills.rel.specialties',
		'system.skills.rel.value': 'A5E.effects.keys.skills.rel.value',

		'system.skills.sci.ability': 'A5E.effects.keys.skills.sci.defaultAbility',
		'system.skills.sci.bonuses.check': 'A5E.effects.keys.skills.sci.checkBonus',
		'system.skills.sci.bonuses.passive': 'A5E.effects.keys.skills.sci.passiveBonus',
		'system.skills.sci.expertiseDice': 'A5E.effects.keys.skills.sci.expertiseDice',
		'system.skills.sci.minRoll': 'A5E.effects.keys.skills.sci.minRoll',
		'system.skills.sci.maxRoll': 'A5E.effects.keys.skills.sci.maxRoll',
		'system.skills.sci.rollMode': 'A5E.effects.keys.skills.sci.rollMode',
		'system.skills.sci.proficient': 'A5E.effects.keys.skills.sci.proficient',
		'system.skills.sci.specialties': 'A5E.effects.keys.skills.sci.specialties',
		'system.skills.sci.value': 'A5E.effects.keys.skills.sci.value',

		'system.skills.slt.ability': 'A5E.effects.keys.skills.slt.defaultAbility',
		'system.skills.slt.bonuses.check': 'A5E.effects.keys.skills.slt.checkBonus',
		'system.skills.slt.bonuses.passive': 'A5E.effects.keys.skills.slt.passiveBonus',
		'system.skills.slt.expertiseDice': 'A5E.effects.keys.skills.slt.expertiseDice',
		'system.skills.slt.minRoll': 'A5E.effects.keys.skills.slt.minRoll',
		'system.skills.slt.maxRoll': 'A5E.effects.keys.skills.slt.maxRoll',
		'system.skills.slt.rollMode': 'A5E.effects.keys.skills.slt.rollMode',
		'system.skills.slt.proficient': 'A5E.effects.keys.skills.slt.proficient',
		'system.skills.slt.specialties': 'A5E.effects.keys.skills.slt.specialties',
		'system.skills.slt.value': 'A5E.effects.keys.skills.slt.value',

		'system.skills.ste.ability': 'A5E.effects.keys.skills.ste.defaultAbility',
		'system.skills.ste.bonuses.check': 'A5E.effects.keys.skills.ste.checkBonus',
		'system.skills.ste.bonuses.passive': 'A5E.effects.keys.skills.ste.passiveBonus',
		'system.skills.ste.expertiseDice': 'A5E.effects.keys.skills.ste.expertiseDice',
		'system.skills.ste.minRoll': 'A5E.effects.keys.skills.ste.minRoll',
		'system.skills.ste.maxRoll': 'A5E.effects.keys.skills.ste.maxRoll',
		'system.skills.ste.rollMode': 'A5E.effects.keys.skills.ste.rollMode',
		'system.skills.ste.proficient': 'A5E.effects.keys.skills.ste.proficient',
		'system.skills.ste.specialties': 'A5E.effects.keys.skills.ste.specialties',
		'system.skills.ste.value': 'A5E.effects.keys.skills.ste.value',

		'system.skills.sur.ability': 'A5E.effects.keys.skills.sur.defaultAbility',
		'system.skills.sur.bonuses.check': 'A5E.effects.keys.skills.sur.checkBonus',
		'system.skills.sur.bonuses.passive': 'A5E.effects.keys.skills.sur.passiveBonus',
		'system.skills.sur.expertiseDice': 'A5E.effects.keys.skills.sur.expertiseDice',
		'system.skills.sur.minRoll': 'A5E.effects.keys.skills.sur.minRoll',
		'system.skills.sur.maxRoll': 'A5E.effects.keys.skills.sur.maxRoll',
		'system.skills.sur.rollMode': 'A5E.effects.keys.skills.sur.rollMode',
		'system.skills.sur.proficient': 'A5E.effects.keys.skills.sur.proficient',
		'system.skills.sur.specialties': 'A5E.effects.keys.skills.sur.specialties',
		'system.skills.sur.value': 'A5E.effects.keys.skills.sur.value',

		// Spell Resources
		'system.spellResources.artifactCharges.current':
			'A5E.effects.keys.spellResources.currentArtifactCharges',
		'system.spellResources.artifactCharges.max':
			'A5E.effects.keys.spellResources.maxArtifactCharges',
		'system.spellResources.inventions.current':
			'A5E.effects.keys.spellResources.currentSpellInventions',
		'system.spellResources.inventions.max': 'A5E.effects.keys.spellResources.maxSpellInventions',
		'system.spellResources.maxPrepared': 'A5E.effects.keys.spellMaxPrepared',
		'system.spellResources.points.current': 'A5E.effects.keys.spellResources.currentSpellPoints',
		'system.spellResources.points.max': 'A5E.effects.keys.spellResources.maxSpellPoints',
		'system.spellResources.slots.1.current': 'A5E.effects.keys.spellResources.currentLevel1Slots',
		'system.spellResources.slots.1.max': 'A5E.effects.keys.spellResources.maxLevel1Slots',
		'system.spellResources.slots.2.current': 'A5E.effects.keys.spellResources.currentLevel2Slots',
		'system.spellResources.slots.2.max': 'A5E.effects.keys.spellResources.maxLevel2Slots',
		'system.spellResources.slots.3.current': 'A5E.effects.keys.spellResources.currentLevel3Slots',
		'system.spellResources.slots.3.max': 'A5E.effects.keys.spellResources.maxLevel3Slots',
		'system.spellResources.slots.4.current': 'A5E.effects.keys.spellResources.currentLevel4Slots',
		'system.spellResources.slots.4.max': 'A5E.effects.keys.spellResources.maxLevel4Slots',
		'system.spellResources.slots.5.current': 'A5E.effects.keys.spellResources.currentLevel5Slots',
		'system.spellResources.slots.5.max': 'A5E.effects.keys.spellResources.maxLevel5Slots',
		'system.spellResources.slots.6.current': 'A5E.effects.keys.spellResources.currentLevel6Slots',
		'system.spellResources.slots.6.max': 'A5E.effects.keys.spellResources.maxLevel6Slots',
		'system.spellResources.slots.7.current': 'A5E.effects.keys.spellResources.currentLevel7Slots',
		'system.spellResources.slots.7.max': 'A5E.effects.keys.spellResources.maxLevel7Slots',
		'system.spellResources.slots.8.current': 'A5E.effects.keys.spellResources.currentLevel8Slots',
		'system.spellResources.slots.8.max': 'A5E.effects.keys.spellResources.maxLevel8Slots',
		'system.spellResources.slots.9.current': 'A5E.effects.keys.spellResources.currentLevel9Slots',
		'system.spellResources.slots.9.max': 'A5E.effects.keys.spellResources.maxLevel9Slots',
		'system.supply': 'A5E.effects.keys.supply',
		'system.traits.alignment': 'A5E.effects.keys.traits.alignment',
		'system.traits.conditionImmunities': 'A5E.effects.keys.traits.conditionImmunities',
		'system.traits.damageImmunities': 'A5E.effects.keys.traits.damageImmunities',
		'system.traits.damageResistances': 'A5E.effects.keys.traits.damageResistances',
		'system.traits.damageVulnerabilities': 'A5E.effects.keys.traits.damageVulnerabilities',
		'system.traits.size': 'A5E.effects.keys.traits.size',
		'@token.light.alpha': 'A5E.effects.keys.token.light.alpha',
		'@token.light.angle': 'A5E.effects.keys.token.light.angle',
		'@token.light.animation.intensity': 'A5E.effects.keys.token.light.animation.intensity',
		'@token.light.animation.reverse': 'A5E.effects.keys.token.light.animation.reverse',
		'@token.light.animation.speed': 'A5E.effects.keys.token.light.animation.speed',
		'@token.light.animation.type': 'A5E.effects.keys.token.light.animation.type',
		'@token.light.attenuation': 'A5E.effects.keys.token.light.attenuation',
		'@token.light.bright': 'A5E.effects.keys.token.light.bright',
		'@token.light.color': 'A5E.effects.keys.token.light.color',
		'@token.light.coloration': 'A5E.effects.keys.token.light.coloration',
		'@token.light.contrast': 'A5E.effects.keys.token.light.contrast',
		'@token.light.darkness.min': 'A5E.effects.keys.token.light.darkness.min',
		'@token.light.darkness.max': 'A5E.effects.keys.token.light.darkness.max',
		'@token.light.dim': 'A5E.effects.keys.token.light.dim',
		'@token.light.luminosity': 'A5E.effects.keys.token.light.luminosity',
		'@token.light.saturation': 'A5E.effects.keys.token.light.saturation',
		'@token.light.shadows': 'A5E.effects.keys.token.light.shadows',
		'@token.light.negative': 'A5E.effects.keys.token.light.negative',

		'@token.texture.src': 'A5E.effects.keys.token.texture.src',
		'@token.texture.scaleX': 'A5E.effects.keys.token.texture.scaleX',
		'@token.texture.scaleY': 'A5E.effects.keys.token.texture.scaleY',
		'@token.width': 'A5E.effects.keys.token.width',
		'@token.height': 'A5E.effects.keys.token.height',
	};

	return { effectsKeyLocalizations };
}
