import registerConditionChanges from "./registerConditionChanges.ts";
import { registerMultiLevelConditions } from "./registerMultiLevelConditions.ts";

export default function registerConditionsConfig() {
  const conditions = {
    blinded: "A5E.conditions.blinded.name",
    bloodied: "A5E.conditions.bloodied.name",
    charmed: "A5E.conditions.charmed.name",
    concentration: "A5E.conditions.concentration.name",
    confused: "A5E.conditions.confused.name",
    corruption: "A5E.conditions.corruption.name",
    dazzled: "A5E.conditions.dazzled.name",
    deafened: "A5E.conditions.deafened.name",
    dead: "A5E.conditions.dead.name",
    doomed: "A5E.conditions.doomed.name",
    encumbered: "A5E.conditions.encumbered.name",
    enervated: "A5E.conditions.enervated.name",
    fatigue: "A5E.conditions.fatigue.name",
    fixated: "A5E.conditions.fixated.name",
    frightened: "A5E.conditions.frightened.name",
    grappled: "A5E.conditions.grappled.name",
    hungover: "A5E.conditions.hungover.name",
    incapacitated: "A5E.conditions.incapacitated.name",
    inebriated: "A5E.conditions.inebriated.name",
    invisible: "A5E.conditions.invisible.name",
    paralyzed: "A5E.conditions.paralyzed.name",
    petrified: "A5E.conditions.petrified.name",
    poisoned: "A5E.conditions.poisoned.name",
    prone: "A5E.conditions.prone.name",
    rattled: "A5E.conditions.rattled.name",
    restrained: "A5E.conditions.restrained.name",
    slowed: "A5E.conditions.slowed.name",
    strife: "A5E.conditions.strife.name",
    stunned: "A5E.conditions.stunned.name",
    unconscious: "A5E.conditions.unconscious.name",
    ...Object.fromEntries(
      Array.from({ length: 10 }, (_, i) => [
        `generic${i + 1}`,
        `Generic ${i + 1}`,
      ]),
    ),
  } as const;

  const conditionDescriptions = {
    blinded: "A5E.conditions.blinded.description",
    bloodied: "A5E.conditions.bloodied.description",
    charmed: "A5E.conditions.charmed.description",
    concentration: "A5E.conditions.concentration.description",
    confused: "A5E.conditions.confused.description",
    corruption: "A5E.conditions.corruption.description",
    dazzled: "A5E.conditions.dazzled.description",
    deafened: "A5E.conditions.deafened.description",
    dead: "A5E.conditions.dead.description",
    doomed: "A5E.conditions.doomed.description",
    encumbered: "A5E.conditions.encumbered.description",
    enervated: "A5E.conditions.enervated.description",
    exhaustion: "A5E.conditions.exhaustion.description",
    fatigue: "A5E.conditions.fatigue.description",
    fixated: "A5E.conditions.fixated.description",
    frightened: "A5E.conditions.frightened.description",
    grappled: "A5E.conditions.grappled.description",
    hungover: "A5E.conditions.hungover.description",
    incapacitated: "A5E.conditions.incapacitated.description",
    inebriated: "A5E.conditions.inebriated.description",
    invisible: "A5E.conditions.invisible.description",
    paralyzed: "A5E.conditions.paralyzed.description",
    petrified: "A5E.conditions.petrified.description",
    poisoned: "A5E.conditions.poisoned.description",
    prone: "A5E.conditions.prone.description",
    rattled: "A5E.conditions.rattled.description",
    restrained: "A5E.conditions.restrained.description",
    slowed: "A5E.conditions.slowed.description",
    strife: "A5E.conditions.strife.description",
    stunned: "A5E.conditions.stunned.description",
    unconscious: "A5E.conditions.unconscious.description",
  } as const;

  const conditionDefaultImages = {
    blinded: "icons/svg/blind.svg",
    bloodied: "icons/svg/blood.svg",
    charmed: "systems/a5e/assets/icons/charmed.svg",
    concentration: "systems/a5e/assets/concentration.svg",
    confused: "systems/a5e/assets/confused.svg",
    corruption: "systems/a5e/assets/corruption.svg",
    dazzled: "systems/a5e/assets/dazzled.svg",
    deafened: "icons/svg/deaf.svg",
    dead: "icons/svg/skull.svg",
    doomed: "systems/a5e/assets/doomed.svg",
    encumbered: "systems/a5e/assets/encumbered.svg",
    enervated: "systems/a5e/assets/enervated.svg",
    exhaustion: "systems/a5e/assets/fatigue.svg",
    fatigue: "systems/a5e/assets/fatigue.svg",
    fixated: "systems/a5e/assets/fixated.svg",
    frightened: "icons/svg/terror.svg",
    grappled: "systems/a5e/assets/grappled.svg",
    hungover: "systems/a5e/assets/hungover.svg",
    incapacitated: "systems/a5e/assets/incapacitated.svg",
    inebriated: "systems/a5e/assets/inebriated.svg",
    invisible: "icons/svg/invisible.svg",
    paralyzed: "icons/svg/paralysis.svg",
    petrified: "systems/a5e/assets/petrified.svg",
    poisoned: "icons/svg/poison.svg",
    prone: "icons/svg/falling.svg",
    rattled: "systems/a5e/assets/rattled.svg",
    restrained: "icons/svg/net.svg",
    slowed: "systems/a5e/assets/slowed.svg",
    strife: "systems/a5e/assets/strife.svg",
    stunned: "icons/svg/daze.svg",
    unconscious: "icons/svg/unconscious.svg",
  } as const;

  const conditionLinkedConditions = {
    paralyzed: ["incapacitated"],
    petrified: ["incapacitated"],
    stunned: ["incapacitated"],
    unconscious: ["incapacitated"],
  } as const;

  const conditionStackableConditions = new Set([
    "corruption",
    "exhaustion ",
    "fatigue",
    "strife",
  ]);

  return {
    conditions,
    conditionDescriptions,
    conditionDefaultImages,
    conditionLinkedConditions,
    conditionStackableConditions,
    ...registerConditionChanges(),
    ...registerMultiLevelConditions(),
  };
}
