export default function registerCharacterClassesConfig() {
	const classSpellLists = {
		artificer: 'A5E.characterClasses.artificer',
		bard: 'A5E.characterClasses.bard',
		cleric: 'A5E.characterClasses.cleric',
		druid: 'A5E.characterClasses.druid',
		elementalistAir: 'A5E.characterClasses.elementalistAir',
		elementalistEarth: 'A5E.characterClasses.elementalistEarth',
		elementalistFire: 'A5E.characterClasses.elementalistFire',
		elementalistWater: 'A5E.characterClasses.elementalistWater',
		herald: 'A5E.characterClasses.herald',
		sorcerer: 'A5E.characterClasses.sorcerer',
		warlock: 'A5E.characterClasses.warlock',
		wielder: 'A5E.characterClasses.wielder',
		witch: 'A5E.characterClasses.witch',
		wizard: 'A5E.characterClasses.wizard',
	};

	const characterClasses = {
		adept: 'A5E.characterClasses.adept',
		artificer: 'A5E.characterClasses.artificer',
		bard: 'A5E.characterClasses.bard',
		berserker: 'A5E.characterClasses.berserker',
		bloodblade: 'A5E.characterClasses.bloodblade',
		cleric: 'A5E.characterClasses.cleric',
		dirgesinger: 'A5E.characterClasses.dirgesinger',
		druid: 'A5E.characterClasses.druid',
		elementalist: 'A5E.characterClasses.elementalist',
		esper: 'A5E.characterClasses.esper',
		fighter: 'A5E.characterClasses.fighter',
		gambler: 'A5E.characterClasses.gambler',
		herald: 'A5E.characterClasses.herald',
		marshal: 'A5E.characterClasses.marshal',
		psion: 'A5E.characterClasses.psion',
		psyknight: 'A5E.characterClasses.psyknight',
		ranger: 'A5E.characterClasses.ranger',
		rogue: 'A5E.characterClasses.rogue',
		savant: 'A5E.characterClasses.savant',
		scholar: 'A5E.characterClasses.scholar',
		scientist: 'A5E.characterClasses.scientist',
		scout: 'A5E.characterClasses.scout',
		sorcerer: 'A5E.characterClasses.sorcerer',
		trooper: 'A5E.characterClasses.trooper',
		warlock: 'A5E.characterClasses.warlock',
		wielder: 'A5E.characterClasses.wielder',
		witch: 'A5E.characterClasses.witch',
		wizard: 'A5E.characterClasses.wizard',
	};

	return { classSpellLists, characterClasses };
}
