export type ProductCategory = 'premium' | 'content' | 'utility';

export interface ProductEntry {
	title: string;
	url: string;
	category: ProductCategory;
	salesPitch?: string;
	abbreviation?: string;
	affiliate?: boolean;
	publisher?: string;
	systems?: string[];
	productLine?: string;
	moduleName?: string;
	moduleDeprecated?: boolean;
}

export const DEPRECATED_MODULE_REASON =
	'The content from this module is included in the core system packs, and the module is no longer necessary.';
export const DEPRECATED_MODULE_PRIORITY: 'low' | 'medium' | 'high' = 'low';

export const publishers: Record<string, string> = {
	acesAdventuringGuides: "Ace's Adventuring Guides",
	anthonyAlipio: 'Anthony Alipio',
	brokenSynapsePress: 'Broken Synapse Press',
	dmSarah: 'DM Sarah',
	enPublishing: 'EN Publishing',
	joshGentry: 'Josh Gentry',
	koboldPress: 'Kobold Press',
	loottheboss: 'LootTheBoss',
	nekroDarkmoon: 'Nekro Darkmoon',
	owlSomeGames: 'Owl(some) Games',
	plantWitchPress: 'Plant Witch Press',
	purpleMartinGames: 'Purple Martin Games',
	ravine: 'Ravine',
	rollThemBones: 'Roll them Bones Gaming',
	roguesCollection: "The Rogue's Collection",
	speaksAndSpells: 'Speaks and Spells Publishing',
	steampunkette: 'Steampunkette',
	variantCodexPress: 'Variant Codex Press',
	wizardsOfTheCoast: 'Wizards of the Coast',
	wolfworksPress: 'Wolfworks Press',
};

export const productLines: Record<string, string> = {
	core: 'Core',
	gpg: 'Gate Pass Gazette',
	moar: 'Manual of Adventurous Resources',
	multiclassersManual: "Multiclasser's Manual",
	scs: 'Single-Class Synergy',
	thematicToolkit: 'Thematic Toolkit',
};

export const products: Record<string, ProductEntry> = {
	acesAdventuringGuideToNecromancy: {
		abbreviation: 'AAGtN',
		affiliate: true,
		category: 'premium',
		publisher: 'acesAdventuringGuides',
		systems: ['a5e'],
		title: "Ace's Adventuring Guide to Necromancy",
		url: 'https://bit.ly/4bez8oK',
		moduleName: 'a5e-aces-necromancy-vol-1',
		moduleDeprecated: true,
	},
	advancedArtificers: {
		abbreviation: 'AA',
		affiliate: true,
		category: 'premium',
		publisher: 'loottheboss',
		systems: ['a5e'],
		title: 'Advanced Artificers',
		url: 'https://www.drivethrurpg.com/en/product/459022/advanced-artificers?affiliate_id=1388381',
		moduleName: 'a5e-advanced-artificers',
		moduleDeprecated: true,
	},
	adventurersGuide: {
		abbreviation: 'AG',
		affiliate: true,
		category: 'premium',
		publisher: 'enPublishing',
		productLine: 'core',
		systems: ['a5e'],
		title: "Level Up: Adventurer's Guide",
		url: 'https://bit.ly/3w15Iua',
		moduleName: 'a5e-adventurers-guide',
		moduleDeprecated: true,
	},
	adventuresInZeitgeist: {
		abbreviation: 'AiZ',
		affiliate: true,
		category: 'premium',
		publisher: 'enPublishing',
		systems: ['a5e'],
		title: 'Level Up: Adventures in ZEITGEIST',
		url: 'https://bit.ly/3u99LnT',
		moduleName: 'a5e-adventures-in-zeitgeist',
		moduleDeprecated: true,
	},
	agentOfTheMagus: {
		abbreviation: 'AotM',
		affiliate: false,
		category: 'premium',
		publisher: 'ravine',
		systems: ['a5e'],
		title: 'Agent of the Magus',
		url: 'https://ravine.itch.io/a5e-subclass01-magus',
		moduleName: 'a5e-agent-of-the-magus',
		moduleDeprecated: true,
	},
	arcaneSniper: {
		abbreviation: 'AS',
		affiliate: true,
		category: 'premium',
		publisher: 'purpleMartinGames',
		productLine: 'multiclassersManual',
		systems: ['a5e'],
		title: 'Arcane Sniper',
		url: 'https://bit.ly/3I3t0SW',
		salesPitch:
			'The Arcane Sniper is a new archetype for rangers that allows you to bolster your archery with spells and infuse your arrows and bolts with powerful enchantments.',
		moduleName: 'a5e-arcane-sniper',
		moduleDeprecated: true,
	},
	bloodyHeretics: {
		abbreviation: 'BH',
		affiliate: true,
		category: 'premium',
		publisher: 'plantWitchPress',
		systems: ['a5e'],
		title: 'Bloody Heretics',
		url: 'https://www.drivethrurpg.com/en/product/498763/bloody-heretics?affiliate_id=1388381',
		moduleName: 'a5e-bloody-heretics',
		moduleDeprecated: true,
	},
	confidenceMage: {
		abbreviation: 'ConfMage',
		affiliate: true,
		category: 'premium',
		publisher: 'purpleMartinGames',
		productLine: 'multiclassersManual',
		systems: ['a5e'],
		title: 'Confidence Mage',
		url: 'https://preview.drivethrurpg.com/en/product/403897/confidence-mage-a5e?affiliate_id=1388381',
		moduleName: 'a5e-confidence-mage',
		moduleDeprecated: true,
	},
	corrosiveSouls: {
		abbreviation: 'CS',
		affiliate: true,
		category: 'premium',
		publisher: 'brokenSynapsePress',
		systems: ['a5e'],
		title: 'Corrosive Souls',
		url: 'https://www.drivethrurpg.com/en/product/511672/corrosive-souls?affiliate_id=1388381',
		moduleName: 'a5e-corrosive-souls',
		moduleDeprecated: true,
	},
	deepMagic1: {
		abbreviation: 'DM Vol.1',
		affiliate: true,
		category: 'premium',
		publisher: 'koboldPress',
		systems: ['5e'],
		title: 'Deep Magic Volume 1',
		url: 'https://bit.ly/3TfgMvP',
		moduleName: 'deep-magic-volume-1',
		moduleDeprecated: true,
	},
	deepMagic2: {
		abbreviation: 'DM Vol.2',
		affiliate: false,
		category: 'premium',
		publisher: 'koboldPress',
		systems: ['5e'],
		title: 'Deep Magic Volume 2',
		url: 'https://bit.ly/3v2z4Zf',
		moduleName: 'deep-magic-volume-2',
		moduleDeprecated: true,
	},
	doesItHit: {
		category: 'utility',
		publisher: 'nekroDarkmoon',
		systems: ['a5e'],
		title: 'Does it hit!?',
		url: 'https://github.com/NekroDarkmoon/does-it-hit-a5e',
		salesPitch: 'A module to help with hit detection and limited damage automation.',
		moduleName: 'does-it-hit-a5e',
	},
	doseOfDungeonpunk: {
		abbreviation: 'DOD:TH',
		affiliate: true,
		category: 'premium',
		publisher: 'joshGentry',
		systems: ['a5e'],
		title: 'Dose of Dungeonpunk - The Talos Heritage',
		url: 'https://bit.ly/4bo5FsM',
		salesPitch:
			'New construct heritage, new items, and a new spell for magically creating talos constructs.',
	},
	dungeonDelversGuide: {
		abbreviation: 'DDG',
		affiliate: true,
		category: 'premium',
		publisher: 'enPublishing',
		productLine: 'core',
		systems: ['a5e'],
		title: "Level Up: Dungeon Delver's Guide",
		url: 'https://bit.ly/4bLImsK',
		moduleName: 'a5e-dungeon-delvers-guide',
		moduleDeprecated: true,
	},
	ecologyOfGravitasHalloween: {
		category: 'content',
		publisher: 'joshGentry',
		systems: ['a5e'],
		title: 'Ecology of Gravitas: Halloween Edition',
		url: 'https://foundryvtt.com/packages/a5e-ecology-of-gravitas-halloween',
		moduleName: 'a5e-ecology-of-gravitas-halloween',
	},
	extraCreditAndDeeperMysteries: {
		abbreviation: 'ECaDM',
		affiliate: true,
		category: 'premium',
		publisher: 'rollThemBones',
		systems: ['a5e'],
		title: 'Extra Credit and Deeper Mysteries',
		url: 'https://bit.ly/47UnJaV',
		moduleName: 'a5e-extra-credits',
		moduleDeprecated: true,
	},
	fableOfFlames: {
		abbreviation: 'FoF',
		affiliate: true,
		category: 'premium',
		publisher: 'owlSomeGames',
		systems: ['a5e'],
		title: 'Fable of Flames',
		url: 'https://www.drivethrurpg.com/en/product/525752/fable-of-flames?affiliate_id=1388381',
		moduleName: 'a5e-fable-of-flames',
		moduleDeprecated: true,
	},
	fieldEngineer: {
		abbreviation: 'FE',
		affiliate: true,
		category: 'premium',
		publisher: 'purpleMartinGames',
		productLine: 'multiclassersManual',
		systems: ['a5e'],
		title: 'Field Engineer',
		url: 'https://bit.ly/49D4FPF',
		moduleName: 'a5e-field-engineer',
		moduleDeprecated: true,
	},
	fieryJustice: {
		abbreviation: 'FJ',
		affiliate: true,
		category: 'premium',
		publisher: 'purpleMartinGames',
		productLine: 'multiclassersManual',
		systems: ['a5e'],
		title: 'Fiery Justice',
		url: 'https://preview.drivethrurpg.com/en/product/409471/fiery-justice-a5e?affiliate_id=1388381',
		salesPitch:
			'Two new archetypes (Berserkers & Heralds), both centered on the fiery wrath of volcanoes.',
		moduleName: 'a5e-fiery-justice',
		moduleDeprecated: true,
	},
	gpg0: {
		abbreviation: 'GPG #0',
		affiliate: true,
		category: 'premium',
		publisher: 'enPublishing',
		productLine: 'gpg',
		systems: ['a5e'],
		title: 'Level Up: Gate Pass Gazette Issue #0',
		url: 'https://bit.ly/3HMhZW5',
		moduleName: 'a5e-gate-pass-gazette-issue-0',
		moduleDeprecated: true,
	},
	gpg1: {
		abbreviation: 'GPG #1',
		affiliate: true,
		category: 'premium',
		publisher: 'enPublishing',
		productLine: 'gpg',
		systems: ['a5e'],
		title: 'Level Up: Gate Pass Gazette Issue #1',
		url: 'https://bit.ly/48YR8BZ',
		moduleName: 'a5e-gate-pass-gazette-issue-1',
		moduleDeprecated: true,
	},
	gpg2: {
		abbreviation: 'GPG #2',
		affiliate: true,
		category: 'premium',
		publisher: 'enPublishing',
		productLine: 'gpg',
		systems: ['a5e'],
		title: 'Level Up: Gate Pass Gazette Issue #2',
		url: 'https://bit.ly/49hj181',
		moduleName: 'a5e-gate-pass-gazette-issue-2',
		moduleDeprecated: true,
	},
	gpg3: {
		abbreviation: 'GPG #3',
		affiliate: true,
		category: 'premium',
		publisher: 'enPublishing',
		productLine: 'gpg',
		systems: ['a5e'],
		title: 'Level Up: Gate Pass Gazette Issue #3',
		url: 'https://bit.ly/49elHTS',
		moduleName: 'a5e-gate-pass-gazette-issue-3',
		moduleDeprecated: true,
	},
	gpg4: {
		abbreviation: 'GPG #4',
		affiliate: true,
		category: 'premium',
		publisher: 'enPublishing',
		productLine: 'gpg',
		systems: ['a5e'],
		title: 'Level Up: Gate Pass Gazette Issue #4',
		url: 'https://bit.ly/4bo5Vbe',
		moduleName: 'a5e-gate-pass-gazette-issue-4',
		moduleDeprecated: true,
	},
	gpg5: {
		abbreviation: 'GPG #5',
		affiliate: true,
		category: 'premium',
		publisher: 'enPublishing',
		productLine: 'gpg',
		systems: ['a5e'],
		title: 'Level Up: Gate Pass Gazette Issue #5',
		url: 'https://bit.ly/3uuw1sx',
		moduleName: 'a5e-gate-pass-gazette-issue-5',
		moduleDeprecated: true,
	},
	gpg6: {
		abbreviation: 'GPG #6',
		affiliate: true,
		category: 'premium',
		publisher: 'enPublishing',
		productLine: 'gpg',
		systems: ['a5e'],
		title: 'Level Up: Gate Pass Gazette Issue #6',
		url: 'https://bit.ly/3SquHyB',
		moduleName: 'a5e-gate-pass-gazette-issue-6',
		moduleDeprecated: true,
	},
	gpg7: {
		abbreviation: 'GPG #7',
		affiliate: true,
		category: 'premium',
		publisher: 'enPublishing',
		productLine: 'gpg',
		systems: ['a5e'],
		title: 'Level Up: Gate Pass Gazette Issue #7',
		url: 'https://bit.ly/4bEHc2h',
		moduleName: 'a5e-gate-pass-gazette-issue-7',
		moduleDeprecated: true,
	},
	gpg8: {
		abbreviation: 'GPG #8',
		affiliate: true,
		category: 'premium',
		publisher: 'enPublishing',
		productLine: 'gpg',
		systems: ['a5e'],
		title: 'Level Up: Gate Pass Gazette Issue #8',
		url: 'https://bit.ly/3SNRHrB',
		moduleName: 'a5e-gate-pass-gazette-issue-8',
		moduleDeprecated: true,
	},
	gpg9: {
		abbreviation: 'GPG #9',
		affiliate: true,
		category: 'premium',
		publisher: 'enPublishing',
		productLine: 'gpg',
		systems: ['a5e'],
		title: 'Level Up: Gate Pass Gazette Issue #9',
		url: 'https://bit.ly/3OvH2k2',
		moduleName: 'a5e-gate-pass-gazette-issue-9',
		moduleDeprecated: true,
	},
	gpg10: {
		abbreviation: 'GPG #10',
		affiliate: true,
		category: 'premium',
		publisher: 'enPublishing',
		productLine: 'gpg',
		systems: ['a5e'],
		title: 'Level Up: Gate Pass Gazette Issue #10',
		url: 'https://bit.ly/42JSXR0',
		moduleName: 'a5e-gate-pass-gazette-issue-10',
		moduleDeprecated: true,
	},
	gpg11: {
		abbreviation: 'GPG #11',
		affiliate: true,
		category: 'premium',
		publisher: 'enPublishing',
		productLine: 'gpg',
		systems: ['a5e'],
		title: 'Level Up: Gate Pass Gazette Issue #11',
		url: 'https://bit.ly/3OsnMnu',
		moduleName: 'a5e-gate-pass-gazette-issue-11',
		moduleDeprecated: true,
	},
	gpg12: {
		abbreviation: 'GPG #12',
		affiliate: true,
		category: 'premium',
		publisher: 'enPublishing',
		productLine: 'gpg',
		systems: ['a5e'],
		title: 'Level Up: Gate Pass Gazette Issue #12',
		url: 'https://bit.ly/3uI2SKn',
		moduleName: 'a5e-gate-pass-gazette-issue-12',
		moduleDeprecated: true,
	},
	gpg13: {
		abbreviation: 'GPG #13',
		affiliate: true,
		category: 'premium',
		publisher: 'enPublishing',
		productLine: 'gpg',
		systems: ['a5e'],
		title: 'Level Up: Gate Pass Gazette Issue #13',
		url: 'https://bit.ly/3T1ABHU',
		moduleName: 'a5e-gate-pass-gazette-issue-13',
		moduleDeprecated: true,
	},
	gpg14: {
		abbreviation: 'GPG #14',
		affiliate: true,
		category: 'premium',
		publisher: 'enPublishing',
		productLine: 'gpg',
		systems: ['a5e'],
		title: 'Level Up: Gate Pass Gazette Issue #14',
		url: 'https://bit.ly/49kSzLo',
		moduleName: 'a5e-gate-pass-gazette-issue-14',
		moduleDeprecated: true,
	},
	gpg15: {
		abbreviation: 'GPG #15',
		affiliate: true,
		category: 'premium',
		publisher: 'enPublishing',
		productLine: 'gpg',
		systems: ['a5e'],
		title: 'Level Up: Gate Pass Gazette Issue #15',
		url: 'https://bit.ly/49kSzLo',
		moduleName: 'a5e-gate-pass-gazette-issue-15',
		moduleDeprecated: true,
	},
	gpg16: {
		abbreviation: 'GPG #16',
		affiliate: true,
		category: 'premium',
		publisher: 'enPublishing',
		productLine: 'gpg',
		systems: ['a5e'],
		title: 'Level Up: Gate Pass Gazette Issue #16',
		url: 'https://bit.ly/3IqpKBv',
		moduleName: 'a5e-gate-pass-gazette-issue-16',
		moduleDeprecated: true,
	},
	gpg17: {
		abbreviation: 'GPG #17',
		affiliate: true,
		category: 'premium',
		publisher: 'enPublishing',
		productLine: 'gpg',
		systems: ['a5e'],
		title: 'Level Up: Gate Pass Gazette Issue #17',
		url: 'https://bit.ly/3uHrm6p',
		moduleName: 'a5e-gate-pass-gazette-issue-17',
		moduleDeprecated: true,
	},
	gpg18: {
		abbreviation: 'GPG #18',
		affiliate: true,
		category: 'premium',
		publisher: 'enPublishing',
		productLine: 'gpg',
		systems: ['a5e'],
		title: 'Level Up: Gate Pass Gazette Issue #18',
		url: 'https://bit.ly/48pPGaX',
		moduleName: 'a5e-gate-pass-gazette-issue-18',
		moduleDeprecated: true,
	},
	gpg19: {
		abbreviation: 'GPG #19',
		affiliate: true,
		category: 'premium',
		publisher: 'enPublishing',
		productLine: 'gpg',
		systems: ['a5e'],
		title: 'Level Up: Gate Pass Gazette Issue #19',
		url: 'https://bit.ly/4blqODO',
		moduleName: 'a5e-gate-pass-gazette-issue-19',
		moduleDeprecated: true,
	},
	gpg20: {
		abbreviation: 'GPG #20',
		affiliate: true,
		category: 'premium',
		publisher: 'enPublishing',
		productLine: 'gpg',
		systems: ['a5e'],
		title: 'Level Up: Gate Pass Gazette Issue #20',
		url: 'https://bit.ly/49OPl2F',
		moduleName: 'a5e-gate-pass-gazette-issue-20',
		moduleDeprecated: true,
	},
	gpg21: {
		abbreviation: 'GPG #21',
		affiliate: true,
		category: 'premium',
		publisher: 'enPublishing',
		productLine: 'gpg',
		systems: ['a5e'],
		title: 'Level Up: Gate Pass Gazette Issue #21',
		url: 'https://bit.ly/4c1jnCf',
		moduleName: 'a5e-gate-pass-gazette-issue-21',
		moduleDeprecated: true,
	},
	hakansPamphlet: {
		abbreviation: 'HPtAW',
		affiliate: false,
		category: 'premium',
		publisher: 'ravine',
		systems: ['a5e'],
		title: "Hakan's Pamphlet to Arcane Weaponry",
		url: 'https://ravine.itch.io/a5e-spells01-arcaneweapon',
		moduleName: 'a5e-arcane-weaponry',
		moduleDeprecated: true,
	},
	hearthAndHome: {
		abbreviation: 'HaH',
		affiliate: true,
		category: 'premium',
		publisher: 'plantWitchPress',
		systems: ['a5e'],
		title: 'Hearth & Home',
		url: 'https://www.drivethrurpg.com/en/product/488835/Hearth--Home-Cozy-Cottage-Origins?affiliate_id=1388381',
		moduleName: 'a5e-hearth-and-home',
		moduleDeprecated: true,
	},
	heroesOldAndNew: {
		abbreviation: 'HOaN',
		affiliate: true,
		category: 'premium',
		publisher: 'rollThemBones',
		systems: ['a5e'],
		title: 'Heroes Old and New',
		url: 'https://bit.ly/3UevPrJ',
		moduleName: 'a5e-heroes-old-and-new',
		moduleDeprecated: true,
	},
	moarComplete: {
		abbreviation: 'MoAR',
		affiliate: true,
		category: 'premium',
		publisher: 'purpleMartinGames',
		productLine: 'moar',
		systems: ['a5e'],
		title: 'Manual of Adventurous Resources: Complete',
		url: 'https://bit.ly/4b7Fsyi',
		moduleName: 'a5e-moar-complete',
		moduleDeprecated: true,
	},
	monstrousMenagerie: {
		abbreviation: 'MoMe',
		affiliate: true,
		category: 'premium',
		publisher: 'enPublishing',
		productLine: 'core',
		systems: ['a5e'],
		title: 'Level Up: Monstrous Menagerie',
		url: 'https://bit.ly/3T1jeqJ',
		moduleName: 'a5e-monstrous-menagerie',
		moduleDeprecated: true,
	},
	mortalist: {
		abbreviation: 'Mort',
		affiliate: true,
		category: 'premium',
		publisher: 'purpleMartinGames',
		productLine: 'multiclassersManual',
		systems: ['a5e'],
		title: 'Mortalist',
		url: 'https://bit.ly/3I6n4Zj',
		moduleName: 'a5e-mortalist',
		moduleDeprecated: true,
	},
	motifClasses: {
		abbreviation: 'SA:MC',
		affiliate: true,
		category: 'premium',
		publisher: 'purpleMartinGames',
		systems: ['a5e'],
		title: 'System Architecture: Motif Classes',
		url: 'https://bit.ly/4bgzU4N',
		moduleName: 'a5e-motif-classes',
		moduleDeprecated: true,
	},
	multiclassersManualVol1: {
		abbreviation: 'MulMan Vol. 1',
		affiliate: true,
		category: 'premium',
		publisher: 'purpleMartinGames',
		productLine: 'multiclassersManual',
		systems: ['a5e'],
		title: "Multiclasser's Manual, Volume 1",
		url: 'https://bit.ly/3JZTA08',
		moduleName: 'a5e-multiclassers-manual',
		moduleDeprecated: true,
	},
	multiclassersManualVol2: {
		abbreviation: 'MulMan Vol. 2',
		affiliate: true,
		category: 'premium',
		publisher: 'purpleMartinGames',
		productLine: 'multiclassersManual',
		systems: ['a5e'],
		title: "Multiclasser's Manual, Volume 2",
		url: 'https://www.drivethrurpg.com/en/product/500104/multiclasser-s-manual-volume-2-a5e?affiliate_id=1388381',
		moduleName: 'a5e-mmv2',
		moduleDeprecated: true,
	},
	mysteriousAndMarvelousMiscellanea: {
		abbreviation: 'MMM',
		affiliate: true,
		category: 'premium',
		publisher: 'rollThemBones',
		systems: ['a5e'],
		title: 'Mysterious and Marvelous Miscellanea',
		url: 'https://bit.ly/42fLLM8',
		moduleName: 'a5e-mmmv2',
		moduleDeprecated: true,
	},
	obscureMedicinals: {
		abbreviation: 'OM',
		affiliate: true,
		category: 'premium',
		publisher: 'variantCodexPress',
		systems: ['a5e'],
		title: 'Obscure Medicinials',
		url: 'https://www.drivethrurpg.com/en/product/507668/obscure-medicinals-for-level-up-a5e?affiliate_id=1388381',
		moduleName: 'a5e-obscure-medicinals',
		moduleDeprecated: true,
	},
	outOfTheWilds: {
		abbreviation: 'OotW',
		affiliate: true,
		category: 'premium',
		publisher: 'plantWitchPress',
		systems: ['a5e'],
		title: 'Out of the Wilds',
		url: 'https://www.drivethrurpg.com/en/product/528982/out-of-the-wilds-a5e?affiliate_id=1388381',
		moduleName: 'out-of-the-wilds',
		moduleDeprecated: true,
	},
	paletteOfHeroes: {
		abbreviation: 'PoH',
		affiliate: true,
		category: 'premium',
		publisher: 'owlSomeGames',
		systems: ['a5e'],
		title: 'The Palette of Heroes',
		url: 'https://www.drivethrurpg.com/en/product/524798/the-palette-of-heroes?affiliate_id=1388381',
		moduleName: 'a5e-the-palette-of-heroes',
		moduleDeprecated: true,
	},
	paradigmsOfSkill: {
		abbreviation: 'PoS',
		affiliate: true,
		category: 'premium',
		publisher: 'plantWitchPress',
		systems: ['a5e'],
		title: 'Paradigms of Skill',
		url: 'https://bit.ly/3TvtZRl',
		moduleName: 'a5e-paradigms-of-skill',
		moduleDeprecated: true,
	},
	paranormalPower: {
		abbreviation: 'PP',
		affiliate: true,
		category: 'premium',
		publisher: 'steampunkette',
		systems: ['a5e'],
		title: 'Paranormal Power',
		url: 'https://bit.ly/49bS1XH',
		moduleName: 'a5e-paranormal-power',
		moduleDeprecated: true,
	},
	ridingParsnip: {
		abbreviation: 'RP',
		affiliate: true,
		category: 'premium',
		publisher: 'purpleMartinGames',
		systems: ['a5e'],
		title: 'Riding Parsnip',
		url: 'https://bit.ly/3xh28Nk',
		moduleName: 'a5e-riding-parsnip',
		moduleDeprecated: true,
	},
	roadWorthyPursuits: {
		abbreviation: 'RWP',
		affiliate: true,
		category: 'premium',
		publisher: 'variantCodexPress',
		systems: ['a5e'],
		title: 'Road Worthy Pursuits',
		url: 'https://www.drivethrurpg.com/en/product/510738/road-worthy-pursuits-expanded-edition-a5e-explorations?affiliate_id=1388381',
		moduleName: 'a5e-road-worthy-pursuits',
		moduleDeprecated: true,
	},
	secretsOfTheSelkies: {
		abbreviation: 'SotS',
		affiliate: true,
		category: 'premium',
		publisher: 'speaksAndSpells',
		systems: ['a5e'],
		title: 'Secrets of the Selkies',
		url: 'https://bit.ly/3USEOix',
		moduleName: 'a5e-secrets-of-the-selkies',
		moduleDeprecated: true,
	},
	singleClassSynergyCoreFour: {
		abbreviation: 'SCS:CF',
		affiliate: true,
		category: 'premium',
		publisher: 'purpleMartinGames',
		productLine: 'scs',
		systems: ['a5e'],
		title: 'Single-Class Synergy, Volume 1: The Core Four',
		url: 'https://www.drivethrurpg.com/en/product/521124/single-class-synergy-volume-1-the-core-four-a5e?affiliate_id=1388381',
		moduleName: 'a5e-core-four',
		moduleDeprecated: true,
	},
	singleClassSynergySingularSpecialists: {
		abbreviation: 'SCS:SS',
		affiliate: true,
		category: 'premium',
		publisher: 'purpleMartinGames',
		productLine: 'scs',
		systems: ['a5e'],
		title: 'Single-Class Synergy, Volume 2: Singular Specialists',
		url: 'https://www.drivethrurpg.com/en/product/526798/single-class-synergy-volume-2-singular-specialists-a5e?affiliate_id=1388381',
		moduleName: 'a5e-singular-specialists',
		moduleDeprecated: true,
	},
	singleClassSynergyHigherCallings: {
		abbreviation: 'SCS:HC',
		affiliate: true,
		category: 'premium',
		publisher: 'purpleMartinGames',
		productLine: 'scs',
		systems: ['a5e'],
		title: 'Single-Class Synergy, Volume 3: Higher Callings',
		url: 'https://www.drivethrurpg.com/en/product/530315/single-class-synergy-volume-3-higher-callings-a5e?affiliate_id=1388381',
		moduleName: 'a5e-higher-callings',
		moduleDeprecated: true,
	},
	sinuousSentinels: {
		abbreviation: 'SinSen',
		affiliate: true,
		category: 'premium',
		publisher: 'purpleMartinGames',
		systems: ['a5e'],
		title: 'Sinuous Sentinels',
		url: 'https://bit.ly/3SSNXoy',
		moduleName: 'a5e-sinuous-sentinels',
		moduleDeprecated: true,
	},
	spellsFromTheForgottenVault: {
		abbreviation: 'SftFV',
		affiliate: true,
		category: 'premium',
		publisher: 'purpleMartinGames',
		systems: ['a5e'],
		title: 'Spells from the Forgotten Vault',
		url: 'https://bit.ly/3T8o5GU',
		moduleName: 'a5e-spells-from-the-forgotten-vault',
		moduleDeprecated: true,
	},
	spiritualist: {
		abbreviation: 'Spirit',
		affiliate: true,
		category: 'premium',
		publisher: 'purpleMartinGames',
		productLine: 'multiclassersManual',
		systems: ['a5e'],
		title: 'Spiritualist',
		url: 'https://preview.drivethrurpg.com/en/product/424846/spiritualist-a5e?affiliate_id=1388381',
		moduleName: 'a5e-spiritualist',
		moduleDeprecated: true,
	},
	strangerSights: {
		abbreviation: 'SS',
		affiliate: true,
		category: 'premium',
		publisher: 'dmSarah',
		systems: ['a5e'],
		title: 'Stranger Sights: Challenges for 5e and Advanced 5e',
		url: 'https://bit.ly/3SmPaEv',
		moduleName: 'a5e-stranger-sights',
		moduleDeprecated: true,
	},
	systemReferenceDocument: {
		abbreviation: 'SRD',
		affiliate: true,
		category: 'premium',
		publisher: 'wizardsOfTheCoast',
		systems: ['a5e'],
		title: 'Dungeons & Dragons 5th Edition System Reference Document',
		url: 'http://bit.ly/3DUPt5G',
		moduleName: 'a5e-dnd5e-srd-content',
		moduleDeprecated: true,
	},
	theHauntingOfCalrowRuins: {
		abbreviation: 'THoCR',
		affiliate: false,
		category: 'premium',
		publisher: 'enPublishing',
		systems: ['a5e'],
		title: 'The Haunting of Calrow Ruins',
		url: 'https://enpublishingrpg.com/products/the-haunting-of-calrow-ruins',
		moduleName: 'a5e-the-haunting-of-calrow-ruins',
		moduleDeprecated: true,
	},
	thematicToolkitArcaneAvenger: {
		abbreviation: 'TT:AA',
		affiliate: true,
		category: 'premium',
		publisher: 'purpleMartinGames',
		productLine: 'thematicToolkit',
		systems: ['a5e'],
		title: 'Thematic Toolkit: Arcane Avenger',
		url: 'https://preview.drivethrurpg.com/en/product/392599/thematic-toolkit-arcane-avenger-a5e?affiliate_id=1388381',
		salesPitch: 'New archetypes for the Herald and Sorcerer classes and a new synergy feat tree.',
		moduleName: 'a5e-thematic-toolkit-arcane-avenger',
		moduleDeprecated: true,
	},
	thematicToolkitBurningGloom: {
		abbreviation: 'TT:BG',
		affiliate: true,
		category: 'premium',
		publisher: 'purpleMartinGames',
		productLine: 'thematicToolkit',
		systems: ['a5e'],
		title: 'Thematic Toolkit: Burning Gloom',
		url: 'https://bit.ly/48XRLfm',
		moduleName: 'a5e-thematic-toolkit-burning-gloom',
		moduleDeprecated: true,
	},
	thematicToolkitCarryTheDarkness: {
		abbreviation: 'TT:CtD',
		affiliate: true,
		category: 'premium',
		publisher: 'purpleMartinGames',
		productLine: 'thematicToolkit',
		systems: ['a5e'],
		title: 'Thematic Toolkit: Carry the Darkness',
		url: 'https://bit.ly/480m03Y',
		moduleName: 'a5e-thematic-toolkit-carry-the-darkness',
		moduleDeprecated: true,
	},
	thematicToolkitCultist: {
		abbreviation: 'TT:Cult',
		affiliate: true,
		category: 'premium',
		publisher: 'purpleMartinGames',
		productLine: 'thematicToolkit',
		systems: ['a5e'],
		title: 'Thematic Toolkit: Cultist',
		url: 'https://preview.drivethrurpg.com/en/product/392588/thematic-toolkit-cultist-a5e?affiliate_id=1388381',
		salesPitch: 'New archetypes for the Cleric and Warlock classes and a new synergy feat tree.',
		moduleName: 'a5e-thematic-toolkit-cultist',
		moduleDeprecated: true,
	},
	thematicToolkitFolkOfTheCourt: {
		abbreviation: 'TT:FotC',
		affiliate: true,
		category: 'premium',
		publisher: 'purpleMartinGames',
		productLine: 'thematicToolkit',
		systems: ['a5e'],
		title: 'Thematic Toolkit: Folk of the Court',
		url: 'https://bit.ly/48SVn1R',
	},
	thematicToolkitHazardousKnowledge: {
		abbreviation: 'TT:HK',
		affiliate: true,
		category: 'premium',
		publisher: 'purpleMartinGames',
		productLine: 'thematicToolkit',
		systems: ['a5e'],
		title: 'Thematic Toolkit: Hazardous Knowledge',
		url: 'https://bit.ly/4d7WzRz',
		moduleName: 'a5e-thematic-toolkit-hazardous-knowledge',
		moduleDeprecated: true,
	},
	thematicToolkitItinerant: {
		abbreviation: 'TT:Itin',
		affiliate: true,
		category: 'premium',
		publisher: 'purpleMartinGames',
		productLine: 'thematicToolkit',
		systems: ['a5e'],
		title: 'Thematic Toolkit: Itinerant',
		url: 'https://bit.ly/3Sidh7p',
		moduleName: 'a5e-thematic-toolkit-itinerant',
		moduleDeprecated: true,
	},
	thematicToolkitJudgeJuryAndExecutioner: {
		abbreviation: 'TT:JJE',
		affiliate: true,
		category: 'premium',
		publisher: 'purpleMartinGames',
		productLine: 'thematicToolkit',
		systems: ['a5e'],
		title: 'Thematic Toolkit: Judge, Jury, and Executioner',
		url: 'https://bit.ly/42OmyZC',
		salesPitch:
			'New archetypes for the Berserker, Herald, and Warlock classes, new backgrounds, a whole bunch of synergy feats.',
		moduleName: 'a5e-thematic-toolkit-judge-jury-and-executioner',
		moduleDeprecated: true,
	},
	thematicToolkitMasterOfCeremonies: {
		abbreviation: 'TT:MoC',
		affiliate: true,
		category: 'premium',
		publisher: 'purpleMartinGames',
		productLine: 'thematicToolkit',
		systems: ['a5e'],
		title: 'Thematic Toolkit: Master of Ceremonies',
		url: 'https://preview.drivethrurpg.com/en/product/422460/thematic-toolkit-master-of-ceremonies-a5e?affiliate_id=1388381',
		moduleName: 'a5e-thematic-toolkit-master-of-ceremonies',
		moduleDeprecated: true,
	},
	thematicToolkitScrapper: {
		abbreviation: 'TT:Scrap',
		affiliate: true,
		category: 'premium',
		publisher: 'purpleMartinGames',
		productLine: 'thematicToolkit',
		systems: ['a5e'],
		title: 'Thematic Toolkit: Scrapper',
		url: 'https://preview.drivethrurpg.com/en/product/412017/thematic-toolkit-scrapper-a5e?affiliate_id=1388381',
		salesPitch: 'New archetypes for the Adept and Fighter classes and a new synergy feat tree.',
		moduleName: 'a5e-thematic-toolkit-scrapper',
		moduleDeprecated: true,
	},
	thematicToolkitStoryteller: {
		abbreviation: 'TT:Story',
		affiliate: true,
		category: 'premium',
		publisher: 'purpleMartinGames',
		productLine: 'thematicToolkit',
		systems: ['a5e'],
		title: 'Thematic Toolkit: Storyteller',
		url: 'https://preview.drivethrurpg.com/en/product/407903/thematic-toolkit-storyteller-a5e?affiliate_id=1388381',
		salesPitch: 'New archetypes for the Bard and Druid classes and a new synergy feat tree.',
		moduleName: 'a5e-thematic-toolkit-storyteller',
		moduleDeprecated: true,
	},
	thematicToolkitThunderOfWar: {
		abbreviation: 'TT:ToW',
		affiliate: true,
		category: 'premium',
		publisher: 'purpleMartinGames',
		productLine: 'thematicToolkit',
		systems: ['a5e'],
		title: 'Thematic Toolkit: Thunder of War',
		url: 'https://preview.drivethrurpg.com/en/product/404207/thematic-toolkit-thunder-of-war-a5e?affiliate_id=1388381',
		salesPitch: 'New archetypes for the Berserker and Marshal classes and a new synergy feat tree.',
		moduleName: 'a5e-thematic-toolkit-thunder-of-war',
		moduleDeprecated: true,
	},
	thematicToolkitVenomousShadow: {
		abbreviation: 'TT:VS',
		affiliate: true,
		category: 'premium',
		publisher: 'purpleMartinGames',
		productLine: 'thematicToolkit',
		systems: ['a5e'],
		title: 'Thematic Toolkit: Venomous Shadow',
		url: 'https://preview.drivethrurpg.com/en/product/400541/thematic-toolkit-venomous-shadow-a5e?affiliate_id=1388381',
		salesPitch:
			'New archetypes for the Ranger, Rogue, and Wizard classes, a whole bunch of synergy feats, and a new combat maneuver tradition.',
		moduleName: 'a5e-thematic-toolkit-venomous-shadow',
		moduleDeprecated: true,
	},
	theErrantSeer: {
		abbreviation: 'TES',
		affiliate: false,
		category: 'premium',
		publisher: 'ravine',
		systems: ['a5e'],
		title: 'The Errant Seer',
		url: 'https://ravine.itch.io/a5e-subclass03-errant-seer',
		moduleName: 'a5e-the-errant-seer',
		moduleDeprecated: true,
	},
	thePodPersonPlague: {
		abbreviation: 'PPP',
		affiliate: true,
		category: 'premium',
		publisher: 'variantCodexPress',
		systems: ['a5e'],
		title: 'The Pod Person Plague: An Ecology of Gravitas for A5E',
		url: 'https://www.drivethrurpg.com/en/product/526974/the-pod-person-plague-an-ecology-of-gravitas-for-a5e?affiliate_id=1388381',
		moduleName: 'a5e-the-pod-person-plague',
		moduleDeprecated: true,
	},
	theRuinStrider: {
		abbreviation: 'TRS',
		affiliate: false,
		category: 'premium',
		publisher: 'ravine',
		systems: ['a5e'],
		title: 'The Ruin Strider',
		url: 'https://ravine.itch.io/a5e-subclass02-ruin-strider',
		moduleName: 'a5e-the-ruin-strider',
		moduleDeprecated: true,
	},
	theSpellbreaker: {
		abbreviation: 'TS',
		affiliate: false,
		category: 'premium',
		publisher: 'ravine',
		systems: ['a5e'],
		title: 'The Spellbreaker',
		url: 'https://ravine.itch.io/a5e-subclass04-spellbreaker',
		moduleName: 'a5e-the-spellbreaker',
		moduleDeprecated: true,
	},
	toilAndTrouble: {
		abbreviation: 'TaT',
		affiliate: true,
		category: 'premium',
		publisher: 'plantWitchPress',
		systems: ['a5e'],
		title: 'Toil and Trouble',
		url: 'https://bit.ly/3HE10VQ',
		moduleName: 'a5e-toil-and-trouble',
		moduleDeprecated: true,
	},
	toSaveAKingdom: {
		abbreviation: 'TSaK',
		affiliate: true,
		category: 'premium',
		publisher: 'enPublishing',
		systems: ['a5e'],
		title: 'Level Up: To Save a Kingdom',
		url: 'https://bit.ly/42iQKvN',
		moduleName: 'a5e-to-save-a-kingdom',
		moduleDeprecated: true,
	},
	trialsAndTreasures: {
		abbreviation: 'T&T',
		affiliate: true,
		category: 'premium',
		publisher: 'enPublishing',
		productLine: 'core',
		systems: ['a5e'],
		title: 'Level Up: Trials and Treasures',
		url: 'https://bit.ly/3w8ha7b',
		moduleName: 'a5e-trials-and-treasures',
		moduleDeprecated: true,
	},
	ventureForth: {
		abbreviation: 'VF',
		affiliate: true,
		category: 'premium',
		publisher: 'speaksAndSpells',
		systems: ['a5e'],
		title: 'Venture Forth',
		url: 'https://bit.ly/49prJRm',
		moduleName: 'a5e-venture-forth',
		moduleDeprecated: true,
	},
	voidrunnersCodex: {
		abbreviation: 'VRC',
		affiliate: true,
		category: 'premium',
		publisher: 'enPublishing',
		systems: ['a5e'],
		title: "Voidrunner's Codex",
		url: 'https://www.drivethrurpg.com/en/product/486863/level-up-voidrunner-s-codex-a5e?affiliate_id=1388381',
		moduleName: 'a5e-voidrunners-codex',
		moduleDeprecated: true,
	},
	wielder: {
		abbreviation: 'W',
		affiliate: true,
		category: 'premium',
		publisher: 'loottheboss',
		systems: ['a5e'],
		title: 'Wielder',
		url: 'https://www.drivethrurpg.com/en/product/518648/wielder-class-a5e-pdf-and-foundry-vtt?affiliate_id=1388381',
		moduleName: 'a5e-wielder',
		moduleDeprecated: true,
	},
};

export const generalModuleIncompatibilities: Record<
	string,
	{ reason: string; priority: 'low' | 'medium' | 'high' }
> = {
	'a5e-concentrator': {
		reason:
			'The A5e concentrator module is no longer working correctly, and its functionality will soon be part of the core system.',
		priority: 'medium',
	},
	'a5e-fancy-compendia': {
		reason:
			'The updated compendium sheets are now included in the A5e system without any need for a module and include several new features. We highly recommend you disable this module to take full advantage of those new features.',
		priority: 'medium',
	},
	dae: {
		reason:
			"All of DAE's features are already part of the A5e system's Active Effects implementation. Using DAE will give you a worse experience than having it turned off.",
		priority: 'high',
	},
	'gamemaster-title-editor': {
		reason:
			"The system already provides settings to configure a GM's title, so this module is unnecessary in the A5e system. It may also conflict with the system's built-in configuration options.",
		priority: 'medium',
	},
	'party-overview': {
		reason:
			'The system already includes an interface to display summary statistics for an adventuring party that provides far more functionality than the Party Overview module.',
		priority: 'low',
	},
};
